apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
  - ../../base
  - namespace.yaml

patches:
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: demo
    target:
      kind: ClusterRoleBinding
      name: demo