apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo
subjects:
  - kind: ServiceAccount
    name: demo
    namespace: default
roleRef:
  kind: ClusterRole
  name: demo
  apiGroup: rbac.authorization.k8s.io

